[package]
name = "pgta"
version = "0.1.0"
authors = ["Lee Fallat <lkfallat@gmail.com>"]

[dependencies]
serde = "1.0.19"
serde_json = "1.0"
serde_derive = "1.0.19"
websocket = "0.20.2"
lazy_static = "0.2"
ggez = "0.3"
circular-queue = "0.2.0"
chrono = "0.4.0"
